### PR TITLE
Patch to correct Readme.md

### PR DESCRIPTION
**Pull request by pethipet**
Correct wrong description in Readme.md

Replace studio_examples.sln with EB_GUIDE_Studio_examples.sln

### CODE REVIEW

**Comment by pethipet** [comment]
Merge  pull request.

**Comment by pethipet** [comment]
Community seems not to be very active here, for now.
This PR was meant as a start, there are some other more issue
e.g. crashes.
But as long as there is not reaction, I'll refrain from making
any additional public changes in my fork or create PRs here.

**Comment by ghost** [comment]
Hi @pethipet, thanks for your input.
We are aware of the mentioned issues and fixes are on the way. This includes also the changes you made with this pull request so I'm going to close this one.

**Comment by pethipet** [comment]
Thanks. I appreciate your update. Especially making it more easy for me to build (before I had a really hard time to only one of the examples build).
May I ask you why through model_extension where just removed with the new commit?
-  TriangleWidget
- DDSTextureLoader
and
- KTXTextureLoader

It was at least somehow educational to look into these, but now they're gone.

Not sure of this (comment in a closed PR) is the right approach to communicate with EB and the EB GUIDE team) - just tried.

**Comment by DeniseZimmermann** [comment]
Hi @pethipet,
thank you for your questions.

We removed the TriangleWidget just for this version as we detected a bug within the example. We could fix the issue, but currently were not able to test this accordingly. With the release of the examples for the next EB GUIDE release the TriangleWidget will be available again.

The DDS- and the KTXTextureLoader were removed as they are still in a draft mode and EB GUIDE Studio changes that are needed to select the textures are not implemented yet.
I hope this helps.
Best regards

**Pull request closed without merging**
